export const colorCopyEmojiList: string[] = [
    '🤟',
    '👏',
    '👌',
    '👏',
    '👍',
    '🤟',
    '🤩',
    '🥳',
    '😂',
    '😍',
    '🤗',
    '😘',
    '👏🏼',
    '🙏',
];

export const colorCopySentences: string[] = [
    'Pretty Good Choice',
    'Hey Nice Choice',
    'Looks Amazing',
    'Brilliant Selection!',
    'Outstanding Choices!',
    'Fantastic Picks!',
    'Superb Taste!',
    'Gorgeous Picks!',
    'Exceptional Picks!',
    'Absolutely Fabulous!',
    'Stellar Selection!',
    'Nailed it!',
    'Fall in Love with Color',
    'Oh wow this is lit',
];
