import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layouts/Navbar';
import Sidebar from '@/components/layouts/Sidebar';
import StoreProvider from '@/Redux/StoreProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <ToastContainer />
                    <div>
                        <Navbar />
                    </div>
                    <div className="flex">
                        <div className="w-64">
                            <Sidebar />
                        </div>
                        <div className='pt-20'>
                            <main>{children}</main>
                        </div>
                    </div>
                </StoreProvider>
            </body>
        </html>
    );
}
